### ISSUE TITLE
Error while try to train the network.

### ISSUE THREAD

**Issue by imostafizur** [lionelmessi6410/Neural-Networks-from-Scratch#4]
Whenever I try to run **python train.py** it shows the following error **KeyError: "None of [Int64Index([38240, 29710, 43652, 15019,  5869, 28379, 12898, 25726, 34628,\n            59007,\n            ...\n            19849, 57726, 14830, 11394,  4489, 58433, 19920, 54449, 34472,\n            47851],\n           dtype='int64', length=60000)] are in the [columns]"**

Thank you

**Comment by JacquelineBashta** [comment]
Same error occur to me! 
@imostafizur any success in solving it?
@lionelmessi6410 Any ideas ? 
Thanks!

**Comment by mmmovania** [comment]
For all those who are still unable to run the provided jupyter notebook. You can try changing these two lines
```
shuffle_index = np.random.permutation(train_size)
x_train, y_train = x_train[shuffle_index], y_train[shuffle_index]
```
to this
```
x_train = np.random.permutation(x_train)
y_train = np.random.permutation(y_train) 
```
